// Copyright © 2026 Ben De St Paer-Gotch
//
// SPDX-License-Identifier: FSL-1.1-ALv2

//! Kernel modules, folded into the generated initramfs so a container-derived
//! guest can see its own devices.
//!
//! # Why this exists
//!
//! Cold boot attaches virtio devices on the MMIO transport. In every arm64
//! distro kernel measured, that transport is a *module*:
//!
//! ```text
//! CONFIG_VIRTIO_MMIO=m      <-- the bus itself
//! CONFIG_VIRTIO_NET=m
//! CONFIG_VIRTIO_BLK=m
//! ```
//!
//! and a container rootfs ships no `/lib/modules`. So the two halves can never
//! meet: the kernel needs modules, and the rootfs `chm image build` writes
//! cannot contain them. The guest boots perfectly and has no network and no
//! disk, under a host log saying the devices are attached. See issue #222.
//!
//! # Why the module's own `.modinfo` is the source of truth
//!
//! Every `.ko` is an ELF object carrying a `.modinfo` section with `name=`,
//! `depends=` and `vermagic=`. This module reads that section rather than the
//! `modules.dep` beside it, for two measured reasons:
//!
//! * **`modules.dep` is not always there.** It is generated by `depmod` when a
//!   package is *installed*, not shipped inside it. Measured:
//!   `linux-modules-6.8.0-71-generic_arm64.deb` contains 916-odd modules and no
//!   `modules.dep` at all.
//! * **`vermagic` is the string the kernel itself compares.** Checking it means
//!   a mismatch is refused on the same authority that would have refused it at
//!   `init_module` time, rather than on a filename we have chosen to trust.
//!
//! That last point is not hypothetical. Alpine's netboot `vmlinuz-virt` and its
//! `linux-virt` apk are both called "virt", both current, and are routinely
//! **different releases** — measured 6.6.134 against 6.6.142 on v3.20, and the
//! same skew on v3.21 and v3.22. Nothing in either name says so, and modules
//! from one silently will not load into the other.
//!
//! # Why the modules are not installed at `lib/modules/...`
//!
//! Because on a usr-merge image `/lib` is a **symlink** to `usr/lib`, and cpio
//! entries are unpacked in sorted order: `./lib/modules/x.ko` is reached before
//! `./usr/lib` exists, the symlink resolves to a directory that is not there
//! yet, and the kernel's unpacker drops the file **without a word**. This is
//! not a guess — it is the same trap [`super::nicfg::GUEST_PATH`] documents
//! having been bitten by, on `node:22-slim`, which is a usr-merge image.
//!
//! So modules land in [`GUEST_DIR`], a directory at the root that no base image
//! can have turned into a symlink, and are loaded by explicit path.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;
use std::fs;
use std::io::{self, Read};
use std::path::{Path, PathBuf};

use flate2::read::GzDecoder;
use zstd::stream::copy_decode;

/// Where the bundled modules are installed in the guest.
///
/// At the root and with a name of our own, for the reason in the module docs:
/// any directory the base image controls may be a symlink, and a symlink that
/// is not resolvable yet costs the file silently.
pub const GUEST_DIR: &str = "gimbal-modules";

/// The drivers a cold-booted guest needs to see the devices chm attaches.
///
/// `virtio_mmio` is the transport and has to come first — loading `virtio_net`
/// without it returns success and still leaves no interface, because the driver
/// registers against a bus that is not there. Ordering is derived from
/// `depends=` rather than from this list; this is only where to start looking.
///
/// A root that is not found here is **not** an error: it means the kernel has
/// that driver built in, which is the outcome we want and the one that needs no
/// help. Measured: Ubuntu's `generic` arm64 kernel ships none of these as
/// modules, because all three are builtin.
/// The drivers a cold-booted guest needs to see the devices chm attaches.
///
/// `virtio_mmio` is the transport and has to come first — loading `virtio_net`
/// without it returns success and still leaves no interface, because the driver
/// registers against a bus that is not there. Ordering is derived from
/// `depends=` rather than from this list; this is only where to start looking.
///
/// A root that is not found here is **not** an error: it means the kernel has
/// that driver built in, which is the outcome we want and the one that needs no
/// help. Measured: Ubuntu's `generic` arm64 kernel ships none of the virtio
/// entries as modules, because they are all builtin.
///
/// `rtc_pl031` is here for a reason that is not obvious: chm attaches a PL031
/// RTC, and without a driver for it the guest's clock starts at the epoch.
/// Nothing says so — the first symptom is that **every TLS handshake fails**
/// with `certificate is not yet valid`, because 1970 predates every certificate
/// the guest will ever be shown. That reads as a network fault and is a clock
/// fault, so `npm install` is impossible and the cause is nowhere in the error.
/// Measured on Ubuntu's `generic` arm64 kernel: no `/dev/rtc*`, guest clock
/// `1970-01-01`, npm refusing the registry's certificate. Alpine's `virt`
/// kernel has PL031 builtin, so this root resolves to nothing there — which is
/// exactly the no-op the "absent means builtin" rule above describes.
pub const MODULE_ROOTS: [&str; 5] = [
    "virtio_mmio",
    "virtio_net",
    "virtio_blk",
    "virtio_pci",
    "rtc_pl031",
];

/// One module, with the metadata read out of its own `.modinfo`.
pub struct Module {
    /// The name the kernel knows it by, from `name=`.
    pub name: String,
    /// Module names this one needs loaded first, from `depends=`.
    pub depends: Vec<String>,
    /// The full `vermagic=` string, e.g. `6.6.142-0-virt SMP preempt …`.
    pub vermagic: String,
    /// The decompressed ELF object, ready to write into the cpio.
    pub image: Vec<u8>,
    /// Where it came from, for messages.
    pub source: PathBuf,
}

impl Module {
    /// Where this module is installed in the guest.
    pub fn guest_path(&self) -> String {
        format!("{GUEST_DIR}/{}.ko", self.name)
    }
}

impl fmt::Debug for Module {
    /// Without this, a failing assertion prints the whole ELF object.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Module")
            .field("name", &self.name)
            .field("depends", &self.depends)
            .field("vermagic", &self.vermagic)
            .field("bytes", &self.image.len())
            .finish()
    }
}

/// A located module tree: `<root>` is a directory holding `kernel/...`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Tree {
    pub root: PathBuf,
    /// How we came to be looking here, so a message can say whether the user
    /// chose this directory or we found it.
    pub found: Found,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Found {
    /// The user passed `--modules`.
    Requested,
    /// Discovered beside the kernel.
    BesideTheKernel,
}

impl Tree {
    pub fn describe(&self) -> String {
        match self.found {
            Found::Requested => format!("{}", self.root.display()),
            Found::BesideTheKernel => format!("{} (found beside the kernel)", self.root.display()),
        }
    }
}

/// Find the module tree for `release`, given what the user asked for.
///
/// `explicit` is `--modules`. It may name either the versioned directory itself
/// or a parent holding `lib/modules/<release>` — someone who has just unpacked
/// a package has the parent, and refusing it would be a puzzle with no purpose.
///
/// With no `--modules`, look beside the kernel, which is where a distro package
/// puts them: a `.deb` unpacks to `boot/vmlinuz-<release>` and
/// `lib/modules/<release>`, and an apk to `boot/vmlinuz-virt` and the same.
///
/// Returns `Ok(None)` when nothing was asked for and nothing was found. That is
/// the ordinary case for a kernel with virtio builtin, and it must not be an
/// error.
/// The module names an initramfs already carries under [`GUEST_DIR`].
///
/// Read out of the archive itself rather than from `image.json` or a flag: the
/// question being answered is *"will this guest have the driver"*, and only the
/// bytes about to be handed to the kernel can answer it. A sidecar saying so
/// would be a claim, and a stale one the first time somebody rebuilds an
/// initramfs in place.
///
/// Best-effort by design. An unreadable or unfamiliar archive yields an empty
/// list, which reinstates the warning -- the safe direction, because the cost
/// of a warning nobody needed is a line of text and the cost of withholding one
/// is a guest with no network and no explanation.
pub fn bundled_in_initramfs(path: &Path) -> Vec<String> {
    let Ok(d) = fs::read(path) else {
        return Vec::new();
    };
    let prefix = format!("{GUEST_DIR}/");
    let mut out = Vec::new();
    let mut i = 0usize;
    // newc, the one format the kernel's own initramfs loader reads.
    while i + 110 <= d.len() {
        if &d[i..i + 6] != b"070701" {
            break;
        }
        let field = |k: usize| -> Option<usize> {
            let raw = d.get(i + 6 + k * 8..i + 6 + (k + 1) * 8)?;
            usize::from_str_radix(str::from_utf8(raw).ok()?, 16).ok()
        };
        let (Some(filesize), Some(namesize)) = (field(6), field(11)) else {
            break;
        };
        if namesize == 0 {
            break;
        }
        let Some(raw) = d.get(i + 110..i + 110 + namesize - 1) else {
            break;
        };
        let name = String::from_utf8_lossy(raw);
        if name == "TRAILER!!!" {
            break;
        }
        let rel = name.trim_start_matches("./");
        if let Some(m) = rel
            .strip_prefix(&prefix)
            .and_then(|f| f.strip_suffix(".ko"))
        {
            out.push(m.to_string());
        }
        let Some(next) = (110 + namesize)
            .checked_next_multiple_of(4)
            .and_then(|h| h.checked_add(filesize.checked_next_multiple_of(4)?))
            .and_then(|step| i.checked_add(step))
        else {
            break;
        };
        if next <= i {
            break;
        }
        i = next;
    }
    out
}

pub fn locate(
    kernel: &Path,
    explicit: Option<&Path>,
    release: &str,
) -> Result<Option<Tree>, String> {
    if let Some(dir) = explicit {
        if !dir.is_dir() {
            return Err(format!("--modules `{}` is not a directory", dir.display()));
        }
        // Accept the versioned directory, a parent holding it, or a
        // `lib/modules` directory pointed at directly -- which is the most
        // natural thing to pass to a flag called `--modules`, and the layout
        // `describe_releases_present` already walks. Omitting it let the
        // refusal enumerate the very release it had just called absent (#254);
        // `every_layout_the_refusal_can_enumerate_is_one_locate_accepts` keeps
        // the two in step.
        for candidate in [
            dir.to_path_buf(),
            dir.join(release),
            dir.join("lib/modules").join(release),
        ] {
            if candidate.join("kernel").is_dir() {
                return Ok(Some(Tree {
                    root: candidate,
                    found: Found::Requested,
                }));
            }
        }
        return Err(format!(
            "--modules `{}` holds no modules for {release}.\n\
             Expected a `kernel/` directory there, or `lib/modules/{release}/kernel/` under it.\n\
             {}",
            dir.display(),
            describe_releases_present(dir),
        ));
    }

    // Beside the kernel. `boot/vmlinuz-x` and `lib/modules/x` are siblings
    // under one root, so look at the kernel's own directory and its parent.
    let mut here = kernel.parent().map(Path::to_path_buf);
    for _ in 0..2 {
        let Some(dir) = here else { break };
        let candidate = dir.join("lib/modules").join(release);
        if candidate.join("kernel").is_dir() {
            return Ok(Some(Tree {
                root: candidate,
                found: Found::BesideTheKernel,
            }));
        }
        here = dir.parent().map(Path::to_path_buf);
    }
    Ok(None)
}

/// Name the releases a directory *does* hold.
///
/// A version mismatch is the single most likely reason to be here, and
/// "expected `lib/modules/6.6.134-0-virt`" next to a directory containing
/// `6.6.142-0-virt` answers the question in one line rather than sending
/// someone to go and look.
fn describe_releases_present(dir: &Path) -> String {
    let mut found: Vec<String> = Vec::new();
    for base in [dir.to_path_buf(), dir.join("lib/modules")] {
        let Ok(entries) = fs::read_dir(&base) else {
            continue;
        };
        for e in entries.flatten() {
            if e.path().join("kernel").is_dir() {
                found.push(e.file_name().to_string_lossy().into_owned());
            }
        }
    }
    found.sort();
    match found.len() {
        0 => "It holds no module tree for any release.".to_string(),
        _ => format!("It holds modules for: {}.", found.join(", ")),
    }
}

/// Every `.ko` in a tree, keyed by the module name its filename implies.
///
/// Built from filenames alone so that locating one module does not cost
/// decompressing all 900. The name a filename implies is a *hint*: the
/// authoritative name is in `.modinfo`, and [`load`] checks the two agree.
pub struct Index {
    by_name: BTreeMap<String, PathBuf>,
}

impl Index {
    pub fn build(tree: &Tree) -> Result<Self, String> {
        let mut by_name = BTreeMap::new();
        walk(&tree.root, &mut |p: &Path| {
            if let Some(name) = module_name_of_file(p) {
                by_name.entry(name).or_insert_with(|| p.to_path_buf());
            }
        })
        .map_err(|e| format!("cannot read `{}`: {e}", tree.root.display()))?;
        if by_name.is_empty() {
            return Err(format!("`{}` holds no kernel modules", tree.root.display()));
        }
        Ok(Self { by_name })
    }

    /// How many modules the tree holds, for reporting how few of them we took.
    pub fn len(&self) -> usize {
        self.by_name.len()
    }

    fn path_of(&self, name: &str) -> Option<&Path> {
        self.by_name.get(name).map(PathBuf::as_path)
    }
}

/// The module name a filename implies.
///
/// Strips every compression suffix we handle, then the `.ko`, then normalises
/// `-` to `_` — the kernel writes `virtio-rng.ko` and calls the module
/// `virtio_rng`, and a lookup that does not normalise misses it.
fn module_name_of_file(path: &Path) -> Option<String> {
    let name = path.file_name()?.to_str()?;
    let stem = name
        .strip_suffix(".gz")
        .or_else(|| name.strip_suffix(".zst"))
        .or_else(|| name.strip_suffix(".xz"))
        .unwrap_or(name);
    let stem = stem.strip_suffix(".ko")?;
    Some(stem.replace('-', "_"))
}

fn walk(dir: &Path, f: &mut impl FnMut(&Path)) -> io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            walk(&path, f)?;
        } else {
            f(&path);
        }
    }
    Ok(())
}

/// What resolving the virtio roots against a tree produced.
#[derive(Debug)]
pub struct Resolved {
    /// Every module to ship, **dependencies before dependents**, which is the
    /// order they must be loaded in.
    pub modules: Vec<Module>,
    /// Roots the tree does not have. Expected and benign: it means the kernel
    /// has that driver builtin.
    pub builtin_or_absent: Vec<String>,
}

impl Resolved {
    pub fn total_bytes(&self) -> usize {
        self.modules.iter().map(|m| m.image.len()).sum()
    }
}

/// Resolve `roots` and everything they depend on, in load order.
///
/// `release` is the kernel's own, from its banner. Every module's `vermagic`
/// must name it: shipping a module that cannot load would produce exactly the
/// silence this whole feature exists to remove, only one layer further in.
pub fn resolve(index: &Index, roots: &[&str], release: &str) -> Result<Resolved, String> {
    let mut modules: Vec<Module> = Vec::new();
    let mut placed: BTreeSet<String> = BTreeSet::new();
    let mut builtin_or_absent = Vec::new();

    for root in roots {
        if index.path_of(root).is_none() {
            builtin_or_absent.push((*root).to_string());
            continue;
        }
        visit(
            index,
            root,
            release,
            &mut placed,
            &mut modules,
            &mut Vec::new(),
        )?;
    }
    Ok(Resolved {
        modules,
        builtin_or_absent,
    })
}

/// Post-order DFS, so a module is pushed only after everything it depends on.
fn visit(
    index: &Index,
    name: &str,
    release: &str,
    placed: &mut BTreeSet<String>,
    out: &mut Vec<Module>,
    stack: &mut Vec<String>,
) -> Result<(), String> {
    if placed.contains(name) {
        return Ok(());
    }
    if stack.iter().any(|s| s == name) {
        // Nothing in a released kernel does this, but a cycle here would
        // otherwise be a stack overflow rather than a message.
        return Err(format!(
            "module dependency cycle: {} -> {name}",
            stack.join(" -> ")
        ));
    }
    let Some(path) = index.path_of(name) else {
        // A dependency, unlike a root, is named by a module that needs it. If
        // it is not here the load will fail, so say so now.
        return Err(format!(
            "`{}` needs module `{name}`, which is not in this module tree",
            stack.last().map_or("(root)", String::as_str)
        ));
    };
    let module = load(path, name, release)?;
    stack.push(name.to_string());
    for dep in module.depends.clone() {
        visit(index, &dep, release, placed, out, stack)?;
    }
    stack.pop();
    placed.insert(name.to_string());
    out.push(module);
    Ok(())
}

/// Read one module: decompress it, parse `.modinfo`, and check it is the module
/// we asked for and is built for this kernel.
fn load(path: &Path, expected_name: &str, release: &str) -> Result<Module, String> {
    let raw =
        fs::read(path).map_err(|e| format!("cannot read module `{}`: {e}", path.display()))?;
    let image = decompress(&raw, path)?;
    let info = modinfo(&image, path)?;

    let name = info
        .get("name")
        .cloned()
        .ok_or_else(|| format!("`{}` carries no module name", path.display()))?;
    if name != expected_name {
        // The filename is a hint and the `.modinfo` is authoritative. Shipping
        // the file under the name we were looking for would install a module
        // the guest then cannot load by that name.
        return Err(format!(
            "`{}` is module `{name}`, not `{expected_name}`",
            path.display()
        ));
    }
    let vermagic = info
        .get("vermagic")
        .cloned()
        .ok_or_else(|| format!("`{}` carries no vermagic", path.display()))?;
    let built_for = vermagic.split(' ').next().unwrap_or_default();
    if built_for != release {
        return Err(format!(
            "module `{name}` is built for kernel {built_for}, but this kernel is {release}.\n\
             The kernel refuses a module whose vermagic does not match, so this would boot to a \
             guest with no devices — the failure this bundling exists to prevent.\n\
             Modules must come from the same kernel package as the kernel itself.\n\
             (from `{}`)",
            path.display()
        ));
    }

    let depends = info
        .get("depends")
        .map(|d| {
            d.split(',')
                .map(str::trim)
                .filter(|s| !s.is_empty())
                .map(|s| s.replace('-', "_"))
                .collect()
        })
        .unwrap_or_default();

    Ok(Module {
        name,
        depends,
        vermagic,
        image,
        source: path.to_path_buf(),
    })
}

/// Decompress a module, choosing the codec by **magic bytes**.
///
/// Not by extension: the same rule the OCI puller and [`crate::kernelimage`]
/// follow, and for the same reason — a name is a claim and the bytes are the
/// fact. A `.ko` that is actually gzipped is then handled, and so is a
/// `.ko.gz` that is not.
fn decompress(raw: &[u8], path: &Path) -> Result<Vec<u8>, String> {
    if raw.starts_with(b"\x7fELF") {
        return Ok(raw.to_vec());
    }
    if raw.starts_with(&[0x1f, 0x8b]) {
        let mut out = Vec::new();
        GzDecoder::new(raw)
            .read_to_end(&mut out)
            .map_err(|e| format!("cannot gunzip `{}`: {e}", path.display()))?;
        return Ok(out);
    }
    if raw.starts_with(&[0x28, 0xb5, 0x2f, 0xfd]) {
        let mut out = Vec::new();
        copy_decode(raw, &mut out)
            .map_err(|e| format!("cannot zstd-decode `{}`: {e}", path.display()))?;
        return Ok(out);
    }
    if raw.starts_with(&[0xfd, b'7', b'z', b'X', b'Z', 0x00]) {
        // Fedora and openSUSE compress modules with xz. Naming it is the
        // difference between "bring a different tree" and a puzzle.
        return Err(format!(
            "`{}` is xz-compressed, which this build cannot decompress.\n\
             Use a module tree compressed with gzip or zstd, or decompress it first.",
            path.display()
        ));
    }
    Err(format!(
        "`{}` is not a kernel module: no ELF header, and not gzip or zstd",
        path.display()
    ))
}

/// Parse the `.modinfo` section of an ELF64 little-endian object.
///
/// The section is a run of NUL-separated `key=value` strings. Only the keys we
/// use are kept; a module carries dozens (author, licence, every parameter).
fn modinfo(image: &[u8], path: &Path) -> Result<BTreeMap<String, String>, String> {
    let bad = |why: &str| format!("cannot read `{}`: {why}", path.display());

    if image.len() < 0x40 || !image.starts_with(b"\x7fELF") {
        return Err(bad("not an ELF object"));
    }
    // ELFCLASS64 and ELFDATA2LSB. An arm64 module is always both, and reading
    // the header of something else would produce nonsense offsets.
    if image[4] != 2 || image[5] != 1 {
        return Err(bad("not a 64-bit little-endian ELF object"));
    }
    let u16_at = |at: usize| u16::from_le_bytes([image[at], image[at + 1]]) as usize;
    let u64_at = |at: usize| -> Option<usize> {
        let b: [u8; 8] = image.get(at..at + 8)?.try_into().ok()?;
        usize::try_from(u64::from_le_bytes(b)).ok()
    };

    let shoff = u64_at(0x28).ok_or_else(|| bad("truncated ELF header"))?;
    let shentsize = u16_at(0x3a);
    let shnum = u16_at(0x3c);
    let shstrndx = u16_at(0x3e);
    if shentsize < 0x40 || shnum == 0 || shstrndx >= shnum {
        return Err(bad("no section headers"));
    }

    let section = |i: usize| -> Option<(usize, usize, usize)> {
        let base = shoff.checked_add(i.checked_mul(shentsize)?)?;
        let name = u32::from_le_bytes(image.get(base..base + 4)?.try_into().ok()?) as usize;
        let off = u64_at(base + 0x18)?;
        let size = u64_at(base + 0x20)?;
        Some((name, off, size))
    };

    let (_, stroff, strsize) = section(shstrndx).ok_or_else(|| bad("bad section header table"))?;
    let strtab = image
        .get(
            stroff
                ..stroff
                    .checked_add(strsize)
                    .ok_or_else(|| bad("bad string table"))?,
        )
        .ok_or_else(|| bad("string table outside the file"))?;

    for i in 0..shnum {
        let Some((name_off, off, size)) = section(i) else {
            continue;
        };
        let Some(rest) = strtab.get(name_off..) else {
            continue;
        };
        let end = rest.iter().position(|&b| b == 0).unwrap_or(rest.len());
        if &rest[..end] != b".modinfo" {
            continue;
        }
        let Some(body) = image.get(off..off.saturating_add(size)) else {
            return Err(bad(".modinfo lies outside the file"));
        };
        let mut out = BTreeMap::new();
        for field in body.split(|&b| b == 0) {
            let Ok(s) = str::from_utf8(field) else {
                continue;
            };
            let Some((k, v)) = s.split_once('=') else {
                continue;
            };
            if matches!(k, "name" | "depends" | "vermagic") {
                out.insert(k.to_string(), v.to_string());
            }
        }
        return Ok(out);
    }
    Err(bad("no .modinfo section — this is not a kernel module"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    /// Build a minimal but *real* ELF64 object with a `.modinfo` section, so
    /// the parser is exercised against the structure it will meet rather than
    /// against a fixture shaped like its own assumptions.
    fn fake_module(fields: &[&str]) -> Vec<u8> {
        let shstrtab = b"\0.modinfo\0.shstrtab\0";
        let mut modinfo = Vec::new();
        for f in fields {
            modinfo.extend_from_slice(f.as_bytes());
            modinfo.push(0);
        }

        let ehsize = 0x40_usize;
        let shentsize = 0x40_usize;
        let modinfo_off = ehsize;
        let shstrtab_off = modinfo_off + modinfo.len();
        let shoff = shstrtab_off + shstrtab.len();

        let mut out = vec![0_u8; shoff];
        out[..4].copy_from_slice(b"\x7fELF");
        out[4] = 2; // ELFCLASS64
        out[5] = 1; // ELFDATA2LSB
        out[0x28..0x30].copy_from_slice(&(shoff as u64).to_le_bytes());
        out[0x3a..0x3c].copy_from_slice(&(shentsize as u16).to_le_bytes());
        out[0x3c..0x3e].copy_from_slice(&3_u16.to_le_bytes()); // shnum
        out[0x3e..0x40].copy_from_slice(&2_u16.to_le_bytes()); // shstrndx
        out[modinfo_off..shstrtab_off].copy_from_slice(&modinfo);
        out[shstrtab_off..shoff].copy_from_slice(shstrtab);

        let mut section = |name: u32, off: usize, size: usize| {
            let mut sh = vec![0_u8; shentsize];
            sh[0..4].copy_from_slice(&name.to_le_bytes());
            sh[0x18..0x20].copy_from_slice(&(off as u64).to_le_bytes());
            sh[0x20..0x28].copy_from_slice(&(size as u64).to_le_bytes());
            out.extend_from_slice(&sh);
        };
        section(0, 0, 0); // SHN_UNDEF
        section(1, modinfo_off, modinfo.len()); // ".modinfo"
        section(10, shstrtab_off, shstrtab.len()); // ".shstrtab"
        out
    }

    fn tree_with(dir: &Path, modules: &[(&str, Vec<u8>)]) -> Tree {
        let kernel = dir.join("kernel/drivers");
        fs::create_dir_all(&kernel).unwrap();
        for (file, body) in modules {
            fs::write(kernel.join(file), body).unwrap();
        }
        Tree {
            root: dir.to_path_buf(),
            found: Found::Requested,
        }
    }

    fn tmp(name: &str) -> PathBuf {
        let p = std::env::temp_dir().join(format!("chm-mod-{}-{name}", std::process::id()));
        let _ = fs::remove_dir_all(&p);
        fs::create_dir_all(&p).unwrap();
        p
    }

    fn gz(data: &[u8]) -> Vec<u8> {
        let mut e = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::fast());
        e.write_all(data).unwrap();
        e.finish().unwrap()
    }

    const REL: &str = "6.6.142-0-virt";
    fn magic() -> String {
        format!("vermagic={REL} SMP preempt mod_unload modversions aarch64")
    }

    #[test]
    fn modinfo_is_read_out_of_a_real_elf_object() {
        let m = fake_module(&["name=virtio_net", "depends=net_failover", &magic()]);
        let info = modinfo(&m, Path::new("x")).unwrap();
        assert_eq!(info.get("name").unwrap(), "virtio_net");
        assert_eq!(info.get("depends").unwrap(), "net_failover");
        assert!(info.get("vermagic").unwrap().starts_with(REL));
    }

    #[test]
    fn dependencies_are_loaded_before_the_modules_that_need_them() {
        let d = tmp("order");
        let t = tree_with(
            &d,
            &[
                (
                    "virtio_net.ko",
                    fake_module(&["name=virtio_net", "depends=net_failover", &magic()]),
                ),
                (
                    "net_failover.ko",
                    fake_module(&["name=net_failover", "depends=failover", &magic()]),
                ),
                (
                    "failover.ko",
                    fake_module(&["name=failover", "depends=", &magic()]),
                ),
            ],
        );
        let idx = Index::build(&t).unwrap();
        let r = resolve(&idx, &["virtio_net"], REL).unwrap();
        let names: Vec<&str> = r.modules.iter().map(|m| m.name.as_str()).collect();
        assert_eq!(names, ["failover", "net_failover", "virtio_net"]);
    }

    /// The whole point of ordering: `virtio_net` loaded before `virtio_mmio`
    /// returns success and still leaves no interface, because the bus it
    /// registers against is not there yet.
    #[test]
    fn the_transport_is_not_left_until_after_the_driver_that_needs_it() {
        let d = tmp("transport");
        let t = tree_with(
            &d,
            &[
                (
                    "virtio_mmio.ko",
                    fake_module(&["name=virtio_mmio", "depends=", &magic()]),
                ),
                (
                    "virtio_net.ko",
                    fake_module(&["name=virtio_net", "depends=virtio_mmio", &magic()]),
                ),
            ],
        );
        let idx = Index::build(&t).unwrap();
        let r = resolve(&idx, &["virtio_net", "virtio_mmio"], REL).unwrap();
        let names: Vec<&str> = r.modules.iter().map(|m| m.name.as_str()).collect();
        assert_eq!(names, ["virtio_mmio", "virtio_net"]);
    }

    /// A root the tree does not have means the kernel has it builtin. Ubuntu's
    /// generic arm64 kernel is exactly this case, and refusing it would refuse
    /// the configuration that already works.
    #[test]
    fn a_missing_root_is_reported_rather_than_refused() {
        let d = tmp("builtin");
        let t = tree_with(
            &d,
            &[(
                "virtio_net.ko",
                fake_module(&["name=virtio_net", "depends=", &magic()]),
            )],
        );
        let idx = Index::build(&t).unwrap();
        let r = resolve(&idx, &["virtio_net", "virtio_blk"], REL).unwrap();
        assert_eq!(r.modules.len(), 1);
        assert_eq!(r.builtin_or_absent, ["virtio_blk"]);
    }

    /// A guest with no RTC driver has no clock, and a guest with no clock fails
    /// every TLS handshake with `certificate is not yet valid` -- an error that
    /// names the network and means the clock. So when a kernel ships the PL031
    /// driver as a module, it has to be bundled like any other device driver.
    ///
    /// Exercised through `resolve` against a real tree rather than asserted
    /// against the constant, so this fails if the root is dropped *or* if the
    /// resolver stops finding it.
    #[test]
    fn the_rtc_driver_is_bundled_when_the_kernel_has_it_as_a_module() {
        let d = tmp("rtc");
        let t = tree_with(
            &d,
            &[
                (
                    "virtio_mmio.ko",
                    fake_module(&["name=virtio_mmio", "depends=", &magic()]),
                ),
                // The kernel writes `rtc-pl031.ko` and calls the module
                // `rtc_pl031`; a lookup that does not normalise misses it.
                (
                    "rtc-pl031.ko",
                    fake_module(&["name=rtc_pl031", "depends=", &magic()]),
                ),
            ],
        );
        let idx = Index::build(&t).unwrap();
        let r = resolve(&idx, &MODULE_ROOTS, REL).unwrap();
        let names: Vec<&str> = r.modules.iter().map(|m| m.name.as_str()).collect();
        assert!(
            names.contains(&"rtc_pl031"),
            "no RTC driver bundled; guest would boot at the epoch. got {names:?}"
        );
    }

    /// A *dependency* is different: something present names it, so its absence
    /// means the load will fail.
    #[test]
    fn a_missing_dependency_is_refused_by_name() {
        let d = tmp("missingdep");
        let t = tree_with(
            &d,
            &[(
                "virtio_net.ko",
                fake_module(&["name=virtio_net", "depends=net_failover", &magic()]),
            )],
        );
        let idx = Index::build(&t).unwrap();
        let e = resolve(&idx, &["virtio_net"], REL).unwrap_err();
        assert!(e.contains("net_failover"), "{e}");
    }

    /// The measured trap: Alpine's netboot kernel and its apk are both "virt",
    /// both current, and different releases.
    #[test]
    fn modules_built_for_another_kernel_are_refused() {
        let d = tmp("vermagic");
        let t = tree_with(
            &d,
            &[(
                "virtio_net.ko",
                fake_module(&["name=virtio_net", "depends=", &magic()]),
            )],
        );
        let idx = Index::build(&t).unwrap();
        let e = resolve(&idx, &["virtio_net"], "6.6.134-0-virt").unwrap_err();
        assert!(e.contains("6.6.142-0-virt"), "{e}");
        assert!(e.contains("6.6.134-0-virt"), "{e}");
    }

    #[test]
    fn a_compressed_module_is_read_by_its_magic_bytes_not_its_name() {
        let d = tmp("gz");
        // Named `.ko`, actually gzipped. The bytes are the fact.
        let t = tree_with(
            &d,
            &[(
                "virtio_blk.ko",
                gz(&fake_module(&["name=virtio_blk", "depends=", &magic()])),
            )],
        );
        let idx = Index::build(&t).unwrap();
        let r = resolve(&idx, &["virtio_blk"], REL).unwrap();
        assert_eq!(r.modules.len(), 1);
        assert!(r.modules[0].image.starts_with(b"\x7fELF"));
    }

    #[test]
    fn a_hyphenated_filename_resolves_to_the_underscored_module_name() {
        assert_eq!(
            module_name_of_file(Path::new("a/virtio-rng.ko.gz")).as_deref(),
            Some("virtio_rng")
        );
        assert_eq!(
            module_name_of_file(Path::new("a/virtio_net.ko.zst")).as_deref(),
            Some("virtio_net")
        );
        assert_eq!(module_name_of_file(Path::new("a/modules.dep")), None);
    }

    /// The filename is a hint; `.modinfo` is authoritative. Shipping a file
    /// under the name we searched for would install a module the guest cannot
    /// then load by that name.
    #[test]
    fn a_file_holding_a_different_module_than_its_name_claims_is_refused() {
        let d = tmp("liar");
        let t = tree_with(
            &d,
            &[(
                "virtio_net.ko",
                fake_module(&["name=e1000", "depends=", &magic()]),
            )],
        );
        let idx = Index::build(&t).unwrap();
        let e = resolve(&idx, &["virtio_net"], REL).unwrap_err();
        assert!(e.contains("e1000"), "{e}");
    }

    #[test]
    fn xz_compression_is_named_rather_than_called_corrupt() {
        let e = decompress(
            &[0xfd, b'7', b'z', b'X', b'Z', 0x00, 0, 0],
            Path::new("m.ko.xz"),
        )
        .unwrap_err();
        assert!(e.contains("xz"), "{e}");
    }

    /// `/lib` is a symlink on a usr-merge image and cpio unpacks in sorted
    /// order, so anything under `lib/` can be silently dropped. This is the
    /// trap `nicfg` was already bitten by.
    #[test]
    fn modules_are_installed_at_the_root_not_under_lib() {
        let d = tmp("guestpath");
        let t = tree_with(
            &d,
            &[(
                "virtio_mmio.ko",
                fake_module(&["name=virtio_mmio", "depends=", &magic()]),
            )],
        );
        let idx = Index::build(&t).unwrap();
        let r = resolve(&idx, &["virtio_mmio"], REL).unwrap();
        let p = r.modules[0].guest_path();
        assert!(!p.starts_with("lib/"), "{p}");
        assert!(!p.contains('/') || p.starts_with(GUEST_DIR), "{p}");
        assert_eq!(p, "gimbal-modules/virtio_mmio.ko");
    }

    #[test]
    fn locate_accepts_either_the_versioned_directory_or_its_parent() {
        let d = tmp("locate");
        let versioned = d.join("lib/modules").join(REL);
        fs::create_dir_all(versioned.join("kernel")).unwrap();
        let kernel = d.join("boot/vmlinuz");
        fs::create_dir_all(d.join("boot")).unwrap();
        fs::write(&kernel, b"x").unwrap();

        let by_parent = locate(&kernel, Some(&d), REL).unwrap().unwrap();
        assert_eq!(by_parent.root, versioned);
        let direct = locate(&kernel, Some(&versioned), REL).unwrap().unwrap();
        assert_eq!(direct.root, versioned);
    }

    /// The layout every distro kernel package ships: `boot/vmlinuz-<rel>` and
    /// `lib/modules/<rel>` as siblings under one root.
    #[test]
    fn modules_are_found_beside_the_kernel() {
        let d = tmp("beside");
        fs::create_dir_all(d.join("lib/modules").join(REL).join("kernel")).unwrap();
        fs::create_dir_all(d.join("boot")).unwrap();
        let kernel = d.join("boot/vmlinuz-virt");
        fs::write(&kernel, b"x").unwrap();
        let t = locate(&kernel, None, REL).unwrap().unwrap();
        assert_eq!(t.found, Found::BesideTheKernel);
    }

    /// Nothing asked for and nothing there is the ordinary case for a kernel
    /// with virtio builtin, and must not be an error.
    #[test]
    fn no_modules_anywhere_is_not_an_error() {
        let d = tmp("none");
        let kernel = d.join("Image");
        fs::write(&kernel, b"x").unwrap();
        assert!(locate(&kernel, None, REL).unwrap().is_none());
    }

    /// The refusal enumerates the releases a directory holds by walking
    /// `<dir>/*/kernel` and `<dir>/lib/modules/*/kernel`. If `locate` accepts
    /// fewer layouts than that walk can name, the message contradicts itself:
    /// "holds no modules for X. It holds modules for: X." (#254).
    ///
    /// So this asserts the invariant rather than one layout: for every place
    /// the enumerator looks, a tree for the *requested* release put there must
    /// be accepted. Adding a base to the walk without teaching `locate` about
    /// it fails here.
    #[test]
    fn every_layout_the_refusal_can_enumerate_is_one_locate_accepts() {
        // The bases `describe_releases_present` scans, relative to `--modules`.
        for base in ["", "lib/modules"] {
            let d = tmp(&format!("enum{}", base.len()));
            let tree = if base.is_empty() {
                d.join(REL)
            } else {
                d.join(base).join(REL)
            };
            fs::create_dir_all(tree.join("kernel")).unwrap();
            let kernel = d.join("Image");
            fs::write(&kernel, b"x").unwrap();

            // It is enumerable: the refusal would be able to name this release.
            let named = describe_releases_present(&d);
            assert!(named.contains(REL), "base `{base}` not enumerable: {named}");

            // Therefore it must be locatable, or the two disagree.
            let got = locate(&kernel, Some(&d), REL).unwrap_or_else(|e| {
                panic!("base `{base}`: enumerated but refused -- {e}");
            });
            assert_eq!(got.expect("a tree").root, tree, "base `{base}`");
            fs::remove_dir_all(&d).ok();
        }
    }

    /// The literal #254 reproduction: pointing `--modules` at a `lib/modules`
    /// directory, which is what the flag's name invites.
    #[test]
    fn a_lib_modules_directory_passed_directly_is_accepted() {
        let d = tmp("libmod");
        let lib_modules = d.join("lib/modules");
        fs::create_dir_all(lib_modules.join(REL).join("kernel")).unwrap();
        let kernel = d.join("Image");
        fs::write(&kernel, b"x").unwrap();
        let t = locate(&kernel, Some(&lib_modules), REL)
            .expect("the layout the refusal used to enumerate")
            .expect("a tree");
        assert_eq!(t.root, lib_modules.join(REL));
    }

    /// A version mismatch is the likeliest reason to be here, so the refusal
    /// says which releases the directory actually holds.
    #[test]
    fn a_directory_with_the_wrong_release_names_what_it_does_have() {
        let d = tmp("wrongrel");
        fs::create_dir_all(d.join("lib/modules/6.6.142-0-virt/kernel")).unwrap();
        let kernel = d.join("Image");
        fs::write(&kernel, b"x").unwrap();
        let e = locate(&kernel, Some(&d), "6.6.134-0-virt").unwrap_err();
        assert!(e.contains("6.6.142-0-virt"), "{e}");
    }

    /// The reader must agree with the writer, and the only way to know is to
    /// use the real writer -- a hand-built fixture and a hand-written parser
    /// agree by construction, which is this repo's recorded #178/#180 failure.
    #[test]
    fn what_the_builder_ships_is_what_the_reader_finds() {
        let mut r = crate::oci::initramfs::Rootfs::default();
        r.insert(
            GUEST_DIR.to_string(),
            crate::oci::entry::EntryKind::Directory { mode: 0o755 },
            Vec::new(),
        );
        for n in ["virtio_mmio", "virtio_net"] {
            r.insert(
                format!("{GUEST_DIR}/{n}.ko"),
                crate::oci::entry::EntryKind::File {
                    mode: 0o644,
                    size: 3,
                },
                vec![1, 2, 3],
            );
        }
        // Ordinary image content, so the scan cannot just be matching ".ko".
        r.insert(
            "usr/lib/modules/other.ko".to_string(),
            crate::oci::entry::EntryKind::File {
                mode: 0o644,
                size: 1,
            },
            vec![0],
        );
        let cpio = crate::oci::initramfs::write_cpio(&r);

        let dir = std::env::temp_dir().join(format!("chm-bundlescan-{}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        let p = dir.join("initramfs");
        fs::write(&p, &cpio).unwrap();
        let mut found = bundled_in_initramfs(&p);
        found.sort();
        fs::remove_dir_all(&dir).ok();

        assert_eq!(
            found,
            vec!["virtio_mmio".to_string(), "virtio_net".to_string()]
        );
    }

    /// An initramfs we cannot read must reinstate the warning, never withhold
    /// it: a line of unnecessary text costs nothing, a guest with no network
    /// and no explanation costs an afternoon.
    #[test]
    fn an_unreadable_initramfs_claims_nothing() {
        let dir = std::env::temp_dir().join(format!("chm-bundlejunk-{}", std::process::id()));
        fs::create_dir_all(&dir).unwrap();
        let p = dir.join("junk");
        fs::write(&p, b"not a cpio at all, not even close").unwrap();
        assert!(bundled_in_initramfs(&p).is_empty());
        assert!(bundled_in_initramfs(&dir.join("does-not-exist")).is_empty());
        // A truncated header must terminate rather than run off the end.
        fs::write(&p, b"070701000000").unwrap();
        assert!(bundled_in_initramfs(&p).is_empty());
        fs::remove_dir_all(&dir).ok();
    }
}
